name: Deploy Python Backend to VPS

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e

            echo "🚀 Deploy started"

            cd /var/www/html/SkinBB_Assistant

            git fetch origin
            git checkout dev
            git reset --hard origin/dev

            source venv/bin/activate

            pip install -r requirements.txt

            sudo systemctl restart chatbot

            echo "✅ Deploy finished"
